ci(default-bare): align with other roles, add default-laurel

diff --git a/.github/workflows/default-bare.yml b/.github/workflows/default-bare.yml
--- a/.github/workflows/default-bare.yml
+++ b/.github/workflows/default-bare.yml
@@ -4,24 +4,49 @@ name: default-bare
 on:
   push:
   pull_request:
+  workflow_dispatch:
   schedule:  # run weekly, every monday 03:00
     - cron: '0 3 * * 1'
 
+permissions: {}
+
 jobs:
   build:
-    runs-on: ${{ matrix.os }}
+    permissions:
+      contents: read
+    runs-on: ${{ matrix.distribution }}-${{ matrix.version }}
+    continue-on-error: ${{ matrix.experimental }}
     strategy:
       fail-fast: false
       max-parallel: 4
       matrix:
-        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
+        include:
+          - distribution: ubuntu
+            version: '24.04'
+            suite: default
+            experimental: true
+          - distribution: ubuntu
+            version: '22.04'
+            suite: default
+            experimental: false
+          - distribution: ubuntu
+            version: '24.04'
+            suite: default-nosyslog
+            experimental: true
+          - distribution: ubuntu
+            version: '24.04'
+            suite: default-laurel
+            experimental: true
     env:
       ANSIBLE_CALLBACKS_ENABLED: profile_tasks
+      ANSIBLE_EXTRA_VARS: ""
+      ANSIBLE_ROLE: juju4.auditd
+      ANSIBLE_SUITE: ${{ matrix.suite }}
 
     steps:
       - uses: actions/checkout@v4
         with:
-          path: juju4.auditd
+          path: ${{ env.ANSIBLE_ROLE }}
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
@@ -37,41 +62,72 @@ jobs:
           ls -l /opt/hostedtoolcache/Python/3.9.1/x64/bin || true
           echo "/opt/hostedtoolcache/Python/3.9.1/x64/bin" >> $GITHUB_PATH
           ansible --version
-          cd $GITHUB_WORKSPACE/juju4.auditd
+          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE
+          [ -f molecule/$ANSIBLE_SUITE/requirements.yml ] && ansible-galaxy install -r molecule/$ANSIBLE_SUITE/requirements.yml
           [ -f get-dependencies.sh ] && sh -x get-dependencies.sh
-          { echo '[defaults]'; echo 'callbacks_enabled = profile_tasks, timer'; echo 'roles_path = ../'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
+          { echo '[defaults]'; echo 'callbacks_enabled = profile_tasks, timer'; echo 'roles_path = ../:/home/runner/.ansible/roles'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
       - name: Environment
         run: |
+          set -x
           pwd
           env
-          find -ls
+          find . -ls
       - name: run test
         run: |
-          cd $GITHUB_WORKSPACE/juju4.auditd && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default/default.yml
+          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/$ANSIBLE_SUITE/default.yml ${ANSIBLE_EXTRA_VARS}
         env:
           PY_COLORS: '1'
           ANSIBLE_FORCE_COLOR: '1'
       - name: idempotency run
         run: |
-          cd $GITHUB_WORKSPACE/juju4.auditd && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/default/default.yml | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 1)
+          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/$ANSIBLE_SUITE/default.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 1)
+      - name: verify - FIXME!
+        run: |
+          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv test/integration/$ANSIBLE_SUITE/verify.yml ${ANSIBLE_EXTRA_VARS}
+        env:
+          PY_COLORS: '1'
+          ANSIBLE_FORCE_COLOR: '1'
       - name: On failure
         run: |
-          systemctl -l --no-pager status auditd
-        if: env.WORKFLOW_CONCLUSION == 'failure'  # notify only if failure
+          systemctl -l --no-pager status
+          systemctl -l --no-pager --failed
+          ls -l /usr/bin/ | egrep '(python|pip|ansible)'
+          pip freeze
+          pip3 freeze
+          ip addr
+          cat /etc/resolv.conf
+          host www.google.com
+          ping -c 1 www.google.com || true
+          ping -c 1 8.8.8.8 || true
+          ps axuw
+          netstat -anp
+        if: ${{ failure() }}
+        continue-on-error: true
+      - name: After script - ansible setup
+        run: |
+          ansible -i inventory --connection=local -m setup localhost
+        if: ${{ always() }}
+        continue-on-error: true
       - name: After script - systemd
         run: |
           set -x
-          systemctl status auditd -l --no-pager
+          systemctl -l --no-pager status auditd || true
+          systemd-analyze --no-pager security || true
+          systemd-analyze --no-pager security auditd || true
+          systemd-analyze --no-pager verify auditd || true
+        if: ${{ always() }}
         continue-on-error: true
       - name: After script - journalctl auditd
         run: |
           set -x
           journalctl -xe -l --no-pager -u auditd | tail -200
+        if: ${{ always() }}
         continue-on-error: true
       - name: After script - journalctl
         run: |
           set -x
           journalctl -xe -l --no-pager | tail -200
+        if: ${{ always() }}
         continue-on-error: true
       - name: After script - rules
         run: |
@@ -79,6 +135,7 @@ jobs:
           sudo ls /etc/audit/rules.d
           sudo cat /etc/audit/audit.rules
           sudo auditctl -l
+        if: ${{ always() }}
         continue-on-error: true
       - name: After script - laurel
         run: |
@@ -87,6 +144,7 @@ jobs:
           sudo cat /etc/audisp/plugins.d/laurel.conf || true
           sudo cat /etc/audit/plugins.d/laurel.conf || true
           /usr/local/sbin/laurel -d -c /etc/laurel/config.toml; echo $?
+        if: ${{ always() }}
         continue-on-error: true
       - name: After script - rsyslog
         run: |
@@ -98,6 +156,7 @@ jobs:
           sudo tail -100 /var/log/audit/audit.log
           sudo -u _laurel tail -100 /var/log/laurel/audit.log
           sudo -u _laurel tail -5 /var/log/laurel/audit.log | jq
+        if: ${{ always() }}
         continue-on-error: true
       - name: After script - report
         run: |
@@ -107,4 +166,5 @@ jobs:
           sudo ls -l /var/log/laurel/
           sudo -u _laurel /usr/local/scripts/auditd_laurel_report.sh
           sudo -u _laurel cat /var/tmp/auditd-laurel-report-*
+        if: ${{ always() }}
         continue-on-error: true
